import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Baloo_Bhaijaan_2, Roboto } from "next/font/google";

const cascadia = localFont({
  src: "./fonts/Cascadia.ttf",
  variable: "--cascadia",
});
const roboto = Roboto({
  weight: "700",
  subsets: ["latin"],
  display: "swap",
});
const balooBhaijaan2 = Baloo_Bhaijaan_2({
  weight: "500",
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${cascadia.variable} ${balooBhaijaan2.className} font-robotto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
